# Generated by Django 5.2.6 on 2025-09-22 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True)),
                ('ai_medicine_rec', models.TextField(blank=True)),
                ('ai_remedies', models.TextField(blank=True)),
                ('ai_precautions', models.TextField(blank=True)),
                ('emergency_video_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
